[build]
  command = "npx ionic build --prod"
  publish = "www"

# Si tu aplicación usa rutas de cliente (Single Page Application - SPA) 
# como es el caso de Angular/Ionic, esto es necesario para evitar 
# errores 404 al recargar la página.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200